export const GET_ABOUT_TEXT_SUCCESS =   'GET_ABOUT_TEXT_SUCCESS';
export const GET_CONNECT_TEXT_SUCCESS = 'GET_CONNECT_TEXT_SUCCESS';
export const GET_HOME_TEXT_SUCCESS =    'GET_HOME_TEXT_SUCCESS';
export const GET_SKILLS_TEXT_SUCCESS =  'GET_SKILLS_TEXT_SUCCESS';
